title: "blabla"
author: "someone"
description: "Really cool website about"
more: "read more"
origin: "https://davidbruant.github.io"
baseurl: "/erights.org"


defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed] # include feed plugin (supported by gh-pages)
