title: "blabla"
author: "someone"
description: "Really cool website about"
more: "read more"
url: "https://erights.org/"
# baseurl: "/writings" # comment out if in root directory


defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed] # include feed plugin (supported by gh-pages)
